apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcq-app-ingress
  namespace: default  # Change to your desired namespace
spec:
  rules:
  - host: 192.168.67.2
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mcq-app-service
            port:
              number: 80
