apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcq-app-ingress
  namespace: prod
spec:
  rules:
  - host: mcq-app-dev.local
    http:
      paths:
      - path: /dev
        pathType: Prefix
        backend:
          service:
            name: mcq-app-service
            port:
              number: 80
