apiVersion: v1
kind: Service
metadata:
  name: mcq-app-service
spec:
  selector:
    app: mcq-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32000
  type: NodePort
