apiVersion: v1
kind: Service
metadata:
  name: mcq-app-service
  namespace: prod
spec:
  selector:
    app: mcq-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31000
  type: NodePort

