apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcq-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcq-app
  template:
    metadata:
      labels:
        app: mcq-app
    spec:
      containers:
        - name: mcq-app
          image: step execution failed: step 3 met error threshold of 1: failed to run step "git-push": invalid git-push config: (root): Must validate one and only one schema (oneOf) targetBranch: targetBranch must be one of the following: "", null
          ports:
            - containerPort: 3000
